### ISSUE TITLE
Leading 0 stripped when dialling from Chrome on Yealink T-48G

### ISSUE THREAD

**Issue by NicolaiL** [turtledialer/doc_turtledialer_chrome#1]
Hi,

Based in the UK where our phone numbers begin with 0. When I dial a contact from Chrome the phone starts dialing but the leading 0 is stripped out, e.g. 01234 567 890 is dialled as 1234567890 which obviously doesn't work.

Would very much appreciate it if this could be fixed.

Thanks

**Comment by ffaraone** [comment]
Hi NicolaiL,

I just uploaded an upgraded version that might fix this bug. Please confirm that the issue is fixed.

**Comment by NicolaiL** [comment]
Hi

 

Thanks for looking into this and for the quick turnaround. However, something is broken so that I can no longer dial any number. When I try to dial a number I can see the number is correctly “translated” e.g +44 1923 883979 is dialled as 01923 883979 but the call is never made. I get a little Turtle dialer pop up window that shows the error (see attached)

 



 

I am wondering if it is the space in the number that causes it to fail on the Action URI?

 

Hope you can fix it :)

 

 

Thanks

 

Nicolai Landschultz

 

Confidentiality Notice: This message is intended for the person/entity to whom it is addressed and may contain privileged and confidential information. Should the reader hereof not be the intended recipient, kindly notify us immediately by return e-mail and delete the original message.

**Comment by ffaraone** [comment]
Hi NocolaiL,

try now the version 1.1.2 and please tell me if it fix this bug.

Thanks

**Comment by NicolaiL** [comment]
Hi

 

Thanks for the new version, but unfortunately there is no change. This still does not work.

 

I have verified that I can make an outbound call form my browser by using the URI directly (e.g. http://192.168.1.43/servlet?key=number=07834892212) but just not from turtle dialler

 

 

Thanks

 

Nicolai Landschultz

 

Confidentiality Notice: This message is intended for the person/entity to whom it is addressed and may contain privileged and confidential information. Should the reader hereof not be the intended recipient, kindly notify us immediately by return e-mail and delete the original message.

**Comment by NicolaiL** [comment]
Hi

 

Just wanted to let you know I have just tested the dialer from a different PC in a different location/phone and it doesn’t work on this PC either.

 

I hope you are able to fix the code? Please let me know if there is any thing I can do to help?

 

 

Thanks

 

Nicolai Landschultz

 

Confidentiality Notice: This message is intended for the person/entity to whom it is addressed and may contain privileged and confidential information. Should the reader hereof not be the intended recipient, kindly notify us immediately by return e-mail and delete the original message.

 

 

From: Nicolai Landschultz <nicolai@landschultz.co.uk>
Date: Friday, 13 May 2016 at 20:31
To: 'turtledialer/doc_turtledialer_chrome' <reply@reply.github.com>, 'turtledialer/doc_turtledialer_chrome' <doc_turtledialer_chrome@noreply.github.com>
Cc: 'Author' <author@noreply.github.com>
Subject: RE: [turtledialer/doc_turtledialer_chrome] Leading 0 stripped when dialling from Chrome on Yealink T-48G (#1)

 

Hi

 

Thanks for the new version, but unfortunately there is no change. This still does not work.

 

I have verified that I can make an outbound call form my browser by using the URI directly (e.g. http://192.168.1.43/servlet?key=number=07834892212) but just not from turtle dialler

 

 

Thanks

 

Nicolai Landschultz

 

Confidentiality Notice: This message is intended for the person/entity to whom it is addressed and may contain privileged and confidential information. Should the reader hereof not be the intended recipient, kindly notify us immediately by return e-mail and delete the original message.

**Comment by ffaraone** [comment]
Hi Nicolai,
I have made some tests on my side and I have seen that, since certain version of chrome, it's not allowed to make ajax calls in https to untrusted servers. Could you please check if turtledialer is configured to talk with the phone in https ? If so, could you please switch to http, restart chrome and try again ?

Thanks

Francesco

**Comment by NicolaiL** [comment]
Hi Francesco

 

I can confirm that my turtledialler is set to use HTTP on port 80.  

 

I can get HTTPS/443 to work by typing in the URL (e.g. https://192.168.1.43/servlet?key=number=07834892212) I do get a load of certificate errors, but ultimately this does work.

 

Not sure why the dialler won’t work over plain HTTP ??

 

One other thing: I noticed that if I bring up the dialler and then manually type a number such as 07834892212 it won’t allow me to dial the number. I have to remove the 0 and then the dialler will try to call the number (but still doesn’t work).

 

 

Thanks

 

Nicolai Landschultz

 

Confidentiality Notice: This message is intended for the person/entity to whom it is addressed and may contain privileged and confidential information. Should the reader hereof not be the intended recipient, kindly notify us immediately by return e-mail and delete the original message.

**Comment by NicolaiL** [comment]
Hi Francesco

 

Is there any way we can move this forward? I’m really keen to get the Turtle dialler working.  

 

I am a developer myself so I would like to offer to help debug the code if you are happy for me to do so?

 

 

Thanks

 

Nicolai Landschultz

 

Confidentiality Notice: This message is intended for the person/entity to whom it is addressed and may contain privileged and confidential information. Should the reader hereof not be the intended recipient, kindly notify us immediately by return e-mail and delete the original message.

 

From: Nicolai Landschultz [mailto:nicolai@landschultz.co.uk] 
Sent: 20 May 2016 19:08
To: 'turtledialer/doc_turtledialer_chrome' <reply@reply.github.com>; 'turtledialer/doc_turtledialer_chrome' <doc_turtledialer_chrome@noreply.github.com>
Cc: 'Author' <author@noreply.github.com>
Subject: RE: [turtledialer/doc_turtledialer_chrome] Leading 0 stripped when dialling from Chrome on Yealink T-48G (#1)

 

Hi Francesco

 

I can confirm that my turtledialler is set to use HTTP on port 80.  

 

I can get HTTPS/443 to work by typing in the URL (e.g. https://192.168.1.43/servlet?key=number=07834892212) I do get a load of certificate errors, but ultimately this does work.

 

Not sure why the dialler won’t work over plain HTTP ??

 

One other thing: I noticed that if I bring up the dialler and then manually type a number such as 07834892212 it won’t allow me to dial the number. I have to remove the 0 and then the dialler will try to call the number (but still doesn’t work).

 

 

Thanks

 

Nicolai Landschultz

 

Confidentiality Notice: This message is intended for the person/entity to whom it is addressed and may contain privileged and confidential information. Should the reader hereof not be the intended recipient, kindly notify us immediately by return e-mail and delete the original message.
